### ISSUE TITLE
Overwrite template

### ISSUE THREAD

**Issue by Mondane** [adamquaile/AdamQuaileFieldsetBundle#2]
Could you change the bundle so overwriting the fieldset_widget in a custom fields.html.twig works?

That file can be set in config.yml:

``` yaml
# Twig Configuration
twig:
    form:
        resources:
            - ':Form:fields.html.twig'
```

Now, I have to copy fieldset.html.twig to /app/Resources/AdamQuaileFieldsetBundle/views/Types/fieldset.html.twig

I believe it's better to follow the structure shown on http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html and https://gist.github.com/spcmky/8512371
